# Generated by Django 2.2.3 on 2019-07-10 13:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        )
    ]
